spring:
  application:
    name: file-upload
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      database: file_management_db
      uri: mongodb+srv://nalandashihan:123@hope.rhtvd.mongodb.net/?retryWrites=true&w=majority&appName=hope

