spring:
  application:
    name: event-management
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      database: event_hope_db
      uri: mongodb+srv://nalandashihan:123@hope.rhtvd.mongodb.net/?retryWrites=true&w=majority&appName=hope
