eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-management
          uri: http://localhost:8070
          predicates:
            - Path=/users/**
        - id: request-management
          uri: http://localhost:8071
          predicates:
            - Path=/requests/**
        - id: event-management
          uri: http://localhost:8072
          predicates:
            - Path=/events/**
        - id: donation-management
          uri: http://localhost:8073
          predicates:
            - Path=/donations/**
        - id: file-upload
          uri: http://localhost:8074
          predicates:
            - Path=/files/**
        - id: validation-service
          uri: http://localhost:8075
          predicates:
            - Path=/validate/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
               - GET
               - POST
               - PUT
               - DELETE
            allowedHeaders: "*"
            allowCredentials: true
